version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - save_cache:
          key: node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - js-set-manipulation/node_modules
  first-build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - js-set-manipulation/node_modules
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm version minor
      - run: npm publish
  
workflows:
  version: 2
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - first-build
      - test:
        requires:
          - first-build
  contibution:
    jobs:
      - build
      - test:
        requires:
          - build
  deployment:
    jobs:
      - first-build
      - test:
        requires:
          - first-build
      - deploy:
        requires:
          - test