version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
      - run: npm install -g jest
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage
      - run: npm test
  
  deploy-minor:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm version minor
      - run: npm publish
  
  deploy-major:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm version major
      - run: npm publish
  
workflows:
  version: 2
  contibution:
    jobs:
      - build
  deployment-minor:
    triggers:
      - schedule:
          # Every week on Wed, Fri 
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy-minor
  deployment-major:
    triggers:
      - schedule:
          # Every 2nd saturday of every month
          cron: "0 0 6 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy-major