version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm version minor
      - run: npm publish