version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
      - restore_cache:
          keys:
            - node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - save_cache:
          key: node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - js-set-manipulation/node_modules
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm version minor
      - run: npm publish
  
# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
# workflows:
#   Welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run