version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - save_cache:
          key: node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules/
  first-build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: node_modules_cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules/
  test-project:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy-project:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm version minor
      - run: npm publish
  
workflows:
  version: 2
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - first-build
      - test-project
  contibution:
    jobs:
      - build
      - test-project
  deployment:
    jobs:
      - first-build
      - test-project
      - deploy-project



# 	0 0 12 ? * WED,FRI *